name: ORAU - Brook

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OfflineResBundleGen
    runs-on: macos-26
    steps:
      - name: Checkout Greatdori!
        uses: actions/checkout@v5
        with:
          repository: "WindowsMEMZ/Greatdori"
          ref: main
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Prepare build directory
        run: mkdir build
      - name: Build OfflineResBundleGen
        run: xcodebuild -project ./Greatdori.xcodeproj -scheme OfflineResBundleGen -configuration Release -derivedDataPath ./build build
      - name: Upload build result
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OfflineResBundleGen.build
          path: ./build
          if-no-files-found: error
  update:
    name: Update Resources
    runs-on: "himmel"
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download OfflineResBundleGen build
        uses: actions/download-artifact@v5.0.0
        with:
          name: OfflineResBundleGen.build
          path: ./build
      - name: Set OfflineResBundleGen path
        id: orbg
        run: echo "path=$(pwd -P)/build/Build/Products/Release/OfflineResBundleGen" >> "$GITHUB_OUTPUT"
      - name: Update main (API)
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout main
          for i in {1..10}; do git pull --rebase && break; done
          "${{ steps.orbg.outputs.path }}" --api -o /Users/himmel/gd-offline-res --max-connection-count 100
          git add .
          git commit -m "Auto update api ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Prepare temporary directory
        run: |
          for i in {1..10}; do rm -rf /Users/himmel/gd-offline-res-tmp && break; done
          mkdir /Users/himmel/gd-offline-res-tmp
      - name: Copy jp/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout jp/basic
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./jp/ /Users/himmel/gd-offline-res-tmp/jp
      - name: Copy jp/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout jp/movie
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./jp/ /Users/himmel/gd-offline-res-tmp/jp
      - name: Copy jp/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout jp/sound
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./jp/ /Users/himmel/gd-offline-res-tmp/jp
      - name: Copy jp/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout jp/unsupported
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./jp/ /Users/himmel/gd-offline-res-tmp/jp
      - name: Update jp/*
        run: |
          cd /Users/himmel/gd-offline-res-tmp
          "${{ steps.orbg.outputs.path }}" --jp -o /Users/himmel/gd-offline-res-tmp --max-connection-count 100
      - name: Apply jp/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          # No need to checkout, we've already in `unsupported` in previous steps
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/characters/ingameresourceset/ /Users/himmel/gd-offline-res/jp/characters/ingameresourceset
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/characters/ingameresourceset
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/live2d/ /Users/himmel/gd-offline-res/jp/live2d
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/live2d
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/musicscore/ /Users/himmel/gd-offline-res/jp/musicscore
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/musicscore
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/pickupsituation/ /Users/himmel/gd-offline-res/jp/pickupsituation
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/pickupsituation
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/star3d/ /Users/himmel/gd-offline-res/jp/star3d
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/star3d
          git add .
          git commit -m "Auto update jp/unsupported ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply jp/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout jp/sound
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/sound/ /Users/himmel/gd-offline-res/jp/sound
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/sound
          git add .
          git commit -m "Auto update jp/sound ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply jp/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout jp/movie
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/movie/ /Users/himmel/gd-offline-res/jp/movie
          rm -rf /Users/himmel/gd-offline-res-tmp/jp/movie
          git add .
          git commit -m "Auto update jp/movie ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply jp/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout jp/basic
          cp -Rf /Users/himmel/gd-offline-res-tmp/jp/ /Users/himmel/gd-offline-res/jp/
          rm -rf /Users/himmel/gd-offline-res-tmp/jp
          git add .
          git commit -m "Auto update jp/basic ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Reset temporary directory
        run: |
          for i in {1..10}; do rm -rf /Users/himmel/gd-offline-res-tmp && break; done
          mkdir /Users/himmel/gd-offline-res-tmp
      - name: Copy en/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout en/basic
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./en/ /Users/himmel/gd-offline-res-tmp/en
      - name: Copy en/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout en/movie
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./en/ /Users/himmel/gd-offline-res-tmp/en
      - name: Copy en/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout en/sound
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./en/ /Users/himmel/gd-offline-res-tmp/en
      - name: Copy en/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout en/unsupported
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./en/ /Users/himmel/gd-offline-res-tmp/en
      - name: Update en/*
        run: |
          cd /Users/himmel/gd-offline-res-tmp
          "${{ steps.orbg.outputs.path }}" --en -o /Users/himmel/gd-offline-res-tmp --max-connection-count 100
      - name: Apply en/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          # No need to checkout, we've already in `unsupported` in previous steps
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/characters/ingameresourceset/ /Users/himmel/gd-offline-res/en/characters/ingameresourceset
          rm -rf /Users/himmel/gd-offline-res-tmp/en/characters/ingameresourceset
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/live2d/ /Users/himmel/gd-offline-res/en/live2d
          rm -rf /Users/himmel/gd-offline-res-tmp/en/live2d
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/musicscore/ /Users/himmel/gd-offline-res/en/musicscore
          rm -rf /Users/himmel/gd-offline-res-tmp/en/musicscore
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/pickupsituation/ /Users/himmel/gd-offline-res/en/pickupsituation
          rm -rf /Users/himmel/gd-offline-res-tmp/en/pickupsituation
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/star3d/ /Users/himmel/gd-offline-res/en/star3d
          rm -rf /Users/himmel/gd-offline-res-tmp/en/star3d
          git add .
          git commit -m "Auto update en/unsupported ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply en/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout en/sound
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/sound/ /Users/himmel/gd-offline-res/en/sound
          rm -rf /Users/himmel/gd-offline-res-tmp/en/sound
          git add .
          git commit -m "Auto update en/sound ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply en/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout en/movie
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/movie/ /Users/himmel/gd-offline-res/en/movie
          rm -rf /Users/himmel/gd-offline-res-tmp/en/movie
          git add .
          git commit -m "Auto update en/movie ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply en/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout en/basic
          cp -Rf /Users/himmel/gd-offline-res-tmp/en/ /Users/himmel/gd-offline-res/en/
          rm -rf /Users/himmel/gd-offline-res-tmp/en
          git add .
          git commit -m "Auto update en/basic ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Reset temporary directory
        run: |
          for i in {1..10}; do rm -rf /Users/himmel/gd-offline-res-tmp && break; done
          mkdir /Users/himmel/gd-offline-res-tmp
      - name: Copy tw/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout tw/basic
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./tw/ /Users/himmel/gd-offline-res-tmp/tw
      - name: Copy tw/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout tw/movie
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./tw/ /Users/himmel/gd-offline-res-tmp/tw
      - name: Copy tw/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout tw/sound
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./tw/ /Users/himmel/gd-offline-res-tmp/tw
      - name: Copy tw/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout tw/unsupported
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./tw/ /Users/himmel/gd-offline-res-tmp/tw
      - name: Update tw/*
        run: |
          cd /Users/himmel/gd-offline-res-tmp
          "${{ steps.orbg.outputs.path }}" --tw -o /Users/himmel/gd-offline-res-tmp --max-connection-count 100
      - name: Apply tw/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          # No need to checkout, we've already in `unsupported` in previous steps
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/characters/ingameresourceset/ /Users/himmel/gd-offline-res/tw/characters/ingameresourceset
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/characters/ingameresourceset
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/live2d/ /Users/himmel/gd-offline-res/tw/live2d
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/live2d
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/musicscore/ /Users/himmel/gd-offline-res/tw/musicscore
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/musicscore
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/pickupsituation/ /Users/himmel/gd-offline-res/tw/pickupsituation
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/pickupsituation
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/star3d/ /Users/himmel/gd-offline-res/tw/star3d
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/star3d
          git add .
          git commit -m "Auto update tw/unsupported ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply tw/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout tw/sound
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/sound/ /Users/himmel/gd-offline-res/tw/sound
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/sound
          git add .
          git commit -m "Auto update tw/sound ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply tw/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout tw/movie
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/movie/ /Users/himmel/gd-offline-res/tw/movie
          rm -rf /Users/himmel/gd-offline-res-tmp/tw/movie
          git add .
          git commit -m "Auto update tw/movie ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply tw/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout tw/basic
          cp -Rf /Users/himmel/gd-offline-res-tmp/tw/ /Users/himmel/gd-offline-res/tw/
          rm -rf /Users/himmel/gd-offline-res-tmp/tw
          git add .
          git commit -m "Auto update tw/basic ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Reset temporary directory
        run: |
          for i in {1..10}; do rm -rf /Users/himmel/gd-offline-res-tmp && break; done
          mkdir /Users/himmel/gd-offline-res-tmp
      - name: Copy cn/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout cn/basic
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./cn/ /Users/himmel/gd-offline-res-tmp/cn
      - name: Copy cn/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout cn/movie
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./cn/ /Users/himmel/gd-offline-res-tmp/cn
      - name: Copy cn/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout cn/sound
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./cn/ /Users/himmel/gd-offline-res-tmp/cn
      - name: Copy cn/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git checkout cn/unsupported
          for i in {1..10}; do git pull --rebase && break; done
          cp -Rf ./cn/ /Users/himmel/gd-offline-res-tmp/cn
      - name: Update cn/*
        run: |
          cd /Users/himmel/gd-offline-res-tmp
          "${{ steps.orbg.outputs.path }}" --cn -o /Users/himmel/gd-offline-res-tmp --max-connection-count 100
      - name: Apply cn/unsupported
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          # No need to checkout, we've already in `unsupported` in previous steps
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/characters/ingameresourceset/ /Users/himmel/gd-offline-res/cn/characters/ingameresourceset
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/characters/ingameresourceset
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/live2d/ /Users/himmel/gd-offline-res/cn/live2d
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/live2d
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/musicscore/ /Users/himmel/gd-offline-res/cn/musicscore
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/musicscore
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/pickupsituation/ /Users/himmel/gd-offline-res/cn/pickupsituation
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/pickupsituation
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/star3d/ /Users/himmel/gd-offline-res/cn/star3d
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/star3d
          git add .
          git commit -m "Auto update cn/unsupported ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply cn/sound
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout cn/sound
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/sound/ /Users/himmel/gd-offline-res/cn/sound
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/sound
          git add .
          git commit -m "Auto update cn/sound ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply cn/movie
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout cn/movie
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/movie/ /Users/himmel/gd-offline-res/cn/movie
          rm -rf /Users/himmel/gd-offline-res-tmp/cn/movie
          git add .
          git commit -m "Auto update cn/movie ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      - name: Apply cn/basic
        env:
          HOME: /Users/himmel
        run: |
          git config --global --add safe.directory /Users/himmel/gd-offline-res
          cd /Users/himmel/gd-offline-res
          git config user.name "Togawa Sakiko"
          git config user.email "sakiko@darock.top"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/WindowsMEMZ/Greatdori-OfflineResBundle.git
          git checkout cn/basic
          cp -Rf /Users/himmel/gd-offline-res-tmp/cn/ /Users/himmel/gd-offline-res/cn/
          rm -rf /Users/himmel/gd-offline-res-tmp/cn
          git add .
          git commit -m "Auto update cn/basic ($(date +"%Y-%m-%d"))" || true
          for i in {1..10}; do git push && break; done
      # Since kr server was closed, we don't update for it
      - name: Clean up temporary directory
        run: for i in {1..10}; do rm -rf /Users/himmel/gd-offline-res-tmp && break; done
