name: Debug

on:
  workflow_dispatch:

jobs:
  build:
    if: false
    name: Build OfflineResBundleGen
    runs-on: "himmel"
    steps:
      - name: Checkout Greatdori!
        uses: actions/checkout@v5
        with:
          repository: "Greatdori/DoriKit"
          ref: main
      - name: Build ORBG
        run: |
          git submodule update --init --recursive
          mkdir build
          xcodebuild -project ./DoriKit.xcodeproj -scheme OfflineResBundleGen -configuration Release -derivedDataPath ./build build
  update:
    name: Update Resources
    runs-on: "himmel"
    needs: build
    if: ${{ always() }}
    permissions:
      contents: write
    steps:
      - name: Set OfflineResBundleGen path
        id: orbg
        run: echo "path=$(pwd -P)/build/Build/Products/Release/OfflineResBundleGen" >> "$GITHUB_OUTPUT"
      - name: Start Debug Script
        env:
          HOME: /Users/himmel
        run: |
          cd /Users/himmel/gd-offline-res
          git checkout main
         # git add .
         # git commit -m "Config .gitignore"
         # git pull
         # pit push
